---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: akeyless-secret
  namespace: external-secrets
  labels:
    external-secrets.io/type: webhook
stringData:
  accessId: ${AKEYLESS_ACCESSID}
  accessType: ${AKEYLESS_ACCESSTYPE}
  accessTypeParam: ${AKEYLESS_ACCESSTYPEPARAM}