[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talosconfig"
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/bootstrap/scripts"
TALOS_DIR = "{{config_root}}/talos"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"python" = "3.14.2"
"uv" = "0.9.16"
"just" = "1.44.1"
"gum" = "0.17.0"
"pipx:makejinja" = "2.8.2"
"pipx:flux-local" = "8.0.1"
"aqua:cilium/cilium-cli" = "0.18.9"
"aqua:cli/cli" = "2.83.1" # GitHub CLI
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:helm/helm" = "3.19.2"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.49.2"
"aqua:siderolabs/talos" = "1.11.5"
"aqua:yannh/kubeconform" = "0.7.0" # Kubernetes manifest validation
