[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/bootstrap/scripts"
TALOS_DIR = "{{config_root}}/talos"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"python" = "3.14.3"
"uv" = "0.10.0"
"just" = "1.46.0"
"gum" = "0.17.0"
"pipx:makejinja" = "2.8.2"
"pipx:flux-local" = "8.1.0"
"aqua:cilium/cilium-cli" = "0.19.0"
"aqua:cli/cli" = "2.86.0" # GitHub CLI
"aqua:cloudflare/cloudflared" = "2026.1.2"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "4.1.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.52.2"
"aqua:siderolabs/talos" = "1.12.2"
"aqua:yannh/kubeconform" = "0.7.0" # Kubernetes manifest validation
