---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 6Gi
  storageClassName: ceph-ssd