---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name guacamole-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # PostgreSQL configuration
        POSTGRESQL_HOSTNAME: "${CNPG_NAME:=pgsql-cluster}-rw.database.svc.cluster.local"
        POSTGRESQL_DATABASE: "${APP}"
        POSTGRESQL_USERNAME: "${APP}"
        POSTGRESQL_PASSWORD: "{{ .${APP}_postgres_password }}"
        # Guacd daemon configuration
        GUACD_HOSTNAME: guacd.observability.svc.cluster.local
        GUACD_PORT: "4822"
        # OpenID Connect (Authentik) configuration
        OPENID_AUTHORIZATION_ENDPOINT: "https://auth.${SECRET_DOMAIN}/application/o/authorize/"
        OPENID_JWKS_ENDPOINT: "https://auth.${SECRET_DOMAIN}/application/o/guacamole/jwks/"
        OPENID_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/guacamole/"
        OPENID_CLIENT_ID: "{{ .GUAC_OIDC_CLIENT_ID }}"
        OPENID_REDIRECT_URI: "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/"
        OPENID_USERNAME_CLAIM_TYPE: "preferred_username"
        OPENID_SCOPE: "openid profile groups email"
  dataFrom:
    - extract:
        key: /authentik
    - extract:
        key: /cnpg-users
