---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name guacamole-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # PostgreSQL configuration
        POSTGRES_HOSTNAME: "${CNPG_NAME:=postgres16}-rw.database.svc.cluster.local"
        POSTGRES_PORT: "5432"
        POSTGRES_DATABASE: "${APP}"
        POSTGRES_USER: "${APP}"
        POSTGRES_PASSWORD: "{{ .${APP}_postgres_password }}"
        # Guacd daemon configuration
        GUACD_HOSTNAME: guacd.observability.svc.cluster.local
        GUACD_PORT: "4822"
        # OpenID Connect (Authentik) configuration
        OPENID_AUTHORIZATION_ENDPOINT: "https://auth.${SECRET_DOMAIN}/application/o/authorize/"
        OPENID_JWKS_ENDPOINT: "https://auth.${SECRET_DOMAIN}/application/o/guacamole/jwks/"
        OPENID_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/guacamole/"
        OPENID_CLIENT_ID: "{{ .GUACAMOLE_OAUTH_CLIENT_ID }}"
        OPENID_REDIRECT_URI: "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}"
  dataFrom:
    - extract:
        key: /guacamole
    - extract:
        key: /cnpg-users
