---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name autobrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
        AUTOBRR__OIDC_CLIENT_ID: "{{ .AUTOBRR_OIDC_CLIENT_ID }}"
        AUTOBRR__OIDC_CLIENT_SECRET: "{{ .AUTOBRR_OIDC_SECRET }}"
        AUTOBRR__OIDC_ISSUER: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/${APP}/"
  dataFrom:
    - extract:
        key: /qbittorrent
    - extract:
        key: /authentik
