
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-outpost-external-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        token: "{{ .AUTHENTIK_OUTPOST_EXTERNAL_TOKEN }}"
  dataFrom:
    - extract:
        key: /authentik
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-outpost-internal-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        token: "{{ .AUTHENTIK_OUTPOST_INTERNAL_TOKEN }}"
  dataFrom:
    - extract:
        key: /authentik
