---
apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost-external
  namespace: default
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/instance: authentik-outpost-external
    app.kubernetes.io/managed-by: goauthentik.io
    # renovate: datasource=docker depName=ghcr.io/goauthentik/proxy
    app.kubernetes.io/version: 2025.12.2
    goauthentik.io/outpost-name: authentik-outpost-external
    goauthentik.io/outpost-type: proxy
    goauthentik.io/outpost-uuid: efb6cd0c1ddd4664804cd0f00b1d220b
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: authentik-outpost-external
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: http
    - name: https
      port: 9443
      protocol: TCP
      targetPort: https
    - name: http-metrics
      port: 9300
      protocol: TCP
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost-external
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: &secret authentik-secret
  labels:
    app.kubernetes.io/name: authentik-outpost-external
    app.kubernetes.io/component: outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-outpost-external
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-outpost-external
        app.kubernetes.io/component: outpost
    spec:
      containers:
        - name: outpost
          image: ghcr.io/goauthentik/proxy:2025.12.2
          env:
            - name: AUTHENTIK_HOST
              value: "http://authentik-server.default.svc.cluster.local"
            - name: AUTHENTIK_INSECURE
              value: "true"
            - name: AUTHENTIK_HOST_BROWSER
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_HOST
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: authentik-outpost-external-token
                  key: token
          envFrom:
            - secretRef:
                name: *secret
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 9300
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-outpost-external
  namespace: default
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /outpost.goauthentik.io
      backendRefs:
        - name: authentik-outpost-external
          port: 9000
