---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./referencegrant.yaml
configMapGenerator:
  - name: authentik-customize
    files:
      - ./resources/custom.css
generatorOptions:
  disableNameSuffixHash: true
