---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-metrics-stack
spec:
  components:
    - ../../../../components/ext-auth-internal
  dependsOn:
    - name: secret-stores
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/observability/victoria-metrics/app
  postBuild:
    substitute:
      APP: vm
      EXT_AUTH_TARGET: vmsingle-stack
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
