---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cnpg-operator
spec:
  dependsOn:
    - name: secret-stores
      namespace: external-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cnpg-cluster
spec:
  dependsOn:
    - name: cnpg-operator
    - name: openebs
      namespace: openebs-system
  healthCheckExprs:
  - apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    failed: status.conditions.filter(e, e.type == 'Ready' && e.status == 'False').size() > 0
    current: status.conditions.filter(e, e.type == 'Ready' && e.status == 'True').size() > 0
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cnpg-secret
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cnpg-immich17
spec:
  dependsOn:
    - name: cnpg-operator
    - name: openebs
      namespace: openebs-system
  healthCheckExprs:
  - apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    failed: status.conditions.filter(e, e.type == 'Ready' && e.status == 'False').size() > 0
    current: status.conditions.filter(e, e.type == 'Ready' && e.status == 'True').size() > 0
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/immich17
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cnpg-secret
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cnpg-barman-cloud
spec:
  dependsOn:
    - name: cnpg-operator
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/barman-cloud
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cnpg-secret
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
