---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: qbittorrent-race-alerts
  labels:
    vmalert-logs.io/enabled: "true"
spec:
  groups:
    - name: &alert1 QbittorrentRaceFastResumeRejected
      type: vlogs
      interval: 5m
      rules:
        - alert: *alert1
          expr: '"fast resume rejected" | filter app := "qbittorrent-race" | count() rows | filter rows :> 0'
          annotations:
            description: '{{ $labels.app }} has a torrent with fast resume rejected'
