---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homebox-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        HBOX_MAILER_HOST: "{{ .SMTP_HOST }}"
        HBOX_MAILER_PORT: "{{ .SMTP_PORT }}"
        HBOX_MAILER_USERNAME: "{{ .SMTP_USERNAME }}"
        HBOX_MAILER_PASSWORD: "{{ .SMTP_PASSWORD }}"
        HBOX_MAILER_FROM: "{{ .SMTP_FROM }}"
        HBOX_OIDC_ISSUER_URL: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/${APP}/"
        HBOX_OIDC_CLIENT_ID: "{{ .HBOX_OIDC_CLIENT_ID }}"
        HBOX_OIDC_CLIENT_SECRET: "{{ .HBOX_OIDC_SECRET }}"
        HBOX_DATABASE_HOST: "${CNPG_NAME:=pgsql-cluster}-rw.database.svc.cluster.local"
        HBOX_DATABASE_PORT: "5432"
        HBOX_DATABASE_DATABASE: "${APP}"
        HBOX_DATABASE_USERNAME: "${APP}"
        HBOX_DATABASE_PASSWORD: "{{ .${APP}_postgres_password }}"
  dataFrom:
    - extract:
        key: /ses-creds
    - extract:
        key: /authentik
    - extract:
        key: /cnpg-users
