---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./certificate.yaml
  # Temporarily commented - will uncomment after HelmRelease installs Gateway API CRDs
  # - ./envoy.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./pushsecret.yaml
