---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.networking.k8s.io/backendtlspolicy_v1alpha3.json
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: &app unifi
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: *app
      sectionName: http  # References the service port named "http" (which is actually HTTPS on 8443)
  options:
    gateway.envoyproxy.io/skip-verify: "true"
  validation:
    wellKnownCACertificates: System
    hostname: unifi.network.svc.cluster.local
