---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name immich17
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: openebs-hostpath

  # # Note: this is needed when recovering from an existing cnpg cluster
  # # https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#restoring-a-cluster
  # bootstrap:
  # #   initdb:
  # #     postInitSQL:
  # #       - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  # #     import:
  # #       databases: ["*"]
  # #       roles: ["*"]
  # #       source:
  # #         externalCluster: &previousCluster immich-v1
  # #       type: monolith
  #   recovery:
  #     source: source
  #     # Only needed for point-in-time recovery
  #     recoveryTarget:
  #       backupID: 20251208T040605
  # externalClusters:
  #   - name: source
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: *name
  #         serverName: *name

  superuserSecret:
    name: cnpg-secret
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries: ["vchord.so"]
    pg_hba: ["host all all 10.42.0.0/16 scram-sha-256"]
    parameters:
      max_connections: "300"
      shared_buffers: 256MB
      autovacuum_vacuum_scale_factor: "0.1"
      autovacuum_analyze_scale_factor: "0.05"
      autovacuum_vacuum_cost_limit: "1000"
      effective_io_concurrency: "200"
      random_page_cost: "1.2"
      work_mem: 16MB
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
  # enablePDB replaces nodeMaintenanceWindow https://cloudnative-pg.io/documentation/1.26/kubernetes_upgrade/#pod-disruption-budgets
  enablePDB: true
  # Fix for non AWS backup https://github.com/cloudnative-pg/cloudnative-pg/issues/7715#issuecomment-2935582020
  env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
    - name: TZ
      value: ${TIMEZONE:-UTC}
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: *name
        serverName: *name
