---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: immich-alerts
  labels:
    vmalert-logs.io/enabled: "true"
spec:
  groups:
    - name: &name ImmichWriteReadOnlyReplica
      type: vlogs
      interval: 5m
      rules:
        - alert: *name
          expr: '_time:5m | "write against a read only replica" | filter app := "immich" | count() rows | filter rows :> 0'
          annotations:
            description: 'Immich is trying to write against a read only replica instead of the primary Redis database'