---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: pgsql-cluster
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "pgsql-cluster.${SECRET_DOMAIN}"
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: pgsql-cluster
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
